=== webkawa/r2pg/web/data/models/components.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified">

    <!-- General tools -->
    <!-- ************* -->
    <xs:simpleType name="string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Complex components -->
    <!-- ****************** -->
    
    <!-- CSS components -->
    <xs:complexType name="css">
        <xs:attribute name="name"
                      use="required"
                      type="string" />   
    </xs:complexType>
    <xs:complexType name="style">
        <xs:sequence>
            <xs:element name="property"
                        type="css" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Selectors -->
    <xs:complexType name="selector">
        <xs:simpleContent>
            <xs:extension base="string">
                <xs:attribute name="id" 
                              type="string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="target">
        <xs:simpleContent>
            <xs:extension base="string">
                <xs:attribute name="refresh"
                              type="xs:boolean" 
                              default="false" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="selectors">
        <xs:sequence>
            <xs:element name="selector"
                        type="selector"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Animation -->
    <xs:simpleType name="easing">
        <xs:restriction base="string">
            <xs:enumeration value="linear" />
            <xs:enumeration value="swing" />
            <xs:enumeration value="easeInQuad" />
            <xs:enumeration value="easeOutQuad" />
            <xs:enumeration value="easeInOutQuad" />
            <xs:enumeration value="easeInCubic" />
            <xs:enumeration value="easeOutCubic" />
            <xs:enumeration value="easeInOutCubic" />
            <xs:enumeration value="easeInQuart" />
            <xs:enumeration value="easeOutQuart" />
            <xs:enumeration value="easeInOutQuart" />
            <xs:enumeration value="easeInQuint" />
            <xs:enumeration value="easeOutQuint" />
            <xs:enumeration value="easeInOutQuint" />
            <xs:enumeration value="easeInSine" />
            <xs:enumeration value="easeOutSine" />
            <xs:enumeration value="easeInOutSine" />
            <xs:enumeration value="easeInExpo" />
            <xs:enumeration value="easeOutExpo" />
            <xs:enumeration value="easeInOutExpo" />
            <xs:enumeration value="easeInCirc" />
            <xs:enumeration value="easeOutCirc" />
            <xs:enumeration value="easeInOutCirc" />
            <xs:enumeration value="easeInElastic" />
            <xs:enumeration value="easeOutElastic" />
            <xs:enumeration value="easeInOutElastic" />
            <xs:enumeration value="easeInBack" />
            <xs:enumeration value="easeOutBack" />
            <xs:enumeration value="easeInOutBack" />
            <xs:enumeration value="easeInBounce" />
            <xs:enumeration value="easeOutBounce" />
            <xs:enumeration value="easeInOutBounce" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="move">
        <xs:all>
            <xs:element name="property"
                        type="string" />
            <xs:element name="from"
                        type="string"
                        minOccurs="0" />
            <xs:element name="to"
                        type="string" />
        </xs:all>
    </xs:complexType>
    <xs:complexType name="animation">
        <xs:sequence>
            <xs:element name="speed"
                        type="xs:decimal" />
            <xs:element name="easing"
                        type="easing" />
            <xs:element name="move"
                        type="move"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Function calls -->
    <xs:complexType name="call">
        <xs:sequence>
            <xs:element name="name" 
                        type="string" />
            <xs:element name="parameter"
                        type="string"
                        minOccurs="0"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Sequence -->
    <xs:complexType name="sequence">
        <xs:sequence>
            <xs:element name="target" 
                        type="target"
                        maxOccurs="unbounded" />
            <xs:element name="precall"
                        type="call"
                        minOccurs="0" />
            <xs:element name="animation" 
                        type="animation" />
            <xs:element name="postcall" 
                        type="call"
                        minOccurs="0" />
            <xs:element name="queue"
                        type="sequence"
                        minOccurs="0"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Loader -->
    <xs:complexType name="loader">
        <xs:sequence>
            <xs:element name="dom"
                        type="string" />
            <xs:element name="action"
                        type="sequence"
                        maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <!-- Trigger -->
    <xs:simpleType name="binder">
        <xs:restriction base="string">
            <xs:enumeration value="click" />
            <xs:enumeration value="mouseup" />
            <xs:enumeration value="mousedown" />
            <xs:enumeration value="mouseover" />
            <xs:enumeration value="mouseout" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="trigger">
        <xs:sequence>
            <xs:element name="target"
                        type="target"
                        maxOccurs="unbounded" />
            <xs:element name="call"
                        type="call" />
        </xs:sequence>
        <xs:attribute name="bind"
                      type="binder"
                      use="required" />
    </xs:complexType>
    
    <!-- State -->
    <xs:complexType name="entry">
        <xs:complexContent>
            <xs:extension base="sequence">
                <xs:attribute name="from"
                              type="string"
                              use="optional" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="exit">
        <xs:complexContent>
            <xs:extension base="sequence">
                <xs:attribute name="to"
                              type="string"
                              use="optional" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="state">
        <xs:sequence>
            <xs:element name="in"
                        type="entry"
                        minOccurs="0" />
            <xs:element name="out"
                        type="exit"
                        minOccurs="0" />
            <xs:element name="selectors"
                        type="selectors"
                        minOccurs="0" />
            <xs:element name="triggers"
                        type="trigger"
                        minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id"
                      type="string" />
    </xs:complexType>
    
    <!-- Main component -->
    <!-- ************** -->
    <xs:simpleType name="classes">
        <xs:restriction base="string">
            <xs:enumeration value="classic" />
            <xs:enumeration value="container" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="component">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="selectors"
                            type="selectors"
                            minOccurs="0" />
                <xs:element name="triggers"
                            type="trigger"
                            minOccurs="0" />
                <xs:element name="loader"
                            type="loader" />
                <xs:element name="state" 
                            type="state" 
                            maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name"
                          type="string" />
            <xs:attribute name="type"
                          type="classes"
                          default="classic" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== webkawa/r2pg/web/data/components/inputs/textfield.xml
<?xml version="1.0" encoding="UTF-8"?>
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../models/components.xsd"
         type="classic" 
         name="InputTextfield" >
    
    <selectors>
        <selector id="wrapper">div.wrapper</selector>
        <selector id="field">div.wrapper > input</selector>
        <selector id="info">div.wrapper > div.info</selector>
    </selectors>
    <loader>
        <dom>
            <![CDATA[
                <div class="wrapper">
                    <input type="textfield"></input>
                    <div class="info"></div>
                </div> 
            ]]>
        </dom>
        <to>Initial</to>
    </loader>
    <waiter>Waiting</waiter>
    <state id="Initial">
        <trigger bind="focus">
            <target>field</target>
            <action call="go">
                <parameter>Focus</parameter>
            </action>
        </trigger>
        <in>
            <pre call="init" />
            <target>wrapper</target>
            <animation>
                <speed>200</speed>
                <easing>swing</easing>
                <move>
                    <property>opacity</property>
                    <from>0</from>
                    <to>1</to>
                </move>
            </animation>
        </in>
    </state>
    <state id="Focus">
        <trigger bind="change">
            <target>field</target>
            <action call="check" />
        </trigger>
    </state>
    <state id="OK">
        <trigger bind="focus">
            <target>field</target>
            <action call="go">
                <parameter>Focus</parameter>
            </action>
        </trigger>
    </state>
    <state id="KO">
        <trigger bind="focus">
            <target>field</target>
            <action call="go">
                <parameter>Focus</parameter>
            </action>
        </trigger>
        <in>
            <target>info</target>
            <animation>
                <speed>200</speed>
                <easing>swing</easing>
                <move>
                    <property>opacity</property>
                    <from>0</from>
                    <to>1</to>
                </move>
            </animation>
        </in>
        <out>
            <target>info</target>
            <animation>
                <speed>200</speed>
                <easing>swing</easing>
                <move>
                    <property>opacity</property>
                    <from>1</from>
                    <to>0</to>
                </move>
            </animation>
        </out>
    </state>
    
</component>

=== webkawa/r2pg/web/data/modules/directUI/inputs/textfield-block.xml
<?xml version="1.0" encoding="UTF-8"?>
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../models/components.xsd"
         name="InputTextfieldBlock" 
         type="classic" >
    
    <selectors>
        <selector id="wrapper">div.wrapper</selector>
        <selector id="head">div.wrapper > div.head</selector>
        <selector id="label">div.wrapper > div.head > label</selector>
        <selector id="description">div.wrapper > div.head > span</selector>
        <selector id="input">div.wrapper > div.input</selector>
        <selector id="field">div.wrapper > div.input > input</selector>
        <selector id="icons">div.wrapper > div.input > div.icon</selector>
        <selector id="locked">div.wrapper > div.input > div.icon.locked</selector>
        <selector id="ok">div.wrapper > div.input > div.icon.ok</selector>
        <selector id="ko">div.wrapper > div.input > div.icon.ko</selector>
        <selector id="focus">div.wrapper > div.input > div.icon.focus</selector>
        <selector id="loading">div.wrapper > div.input > div.icon.loading</selector>
        <selector id="foot">div.wrapper > div.foot</selector>
    </selectors>
    <trajectories>
        <trajectory name="fadein">
            <speed>320</speed>
            <easing>easeInQuart</easing>
            <move>
                <property>opacity</property>
                <from>0</from>
                <to>1</to>
            </move>
        </trajectory>
        <trajectory name="fadeout">
            <speed>320</speed>
            <easing>easeOutQuart</easing>
            <move>
                <property>opacity</property>
                <from>1</from>
                <to>0</to>
            </move>
        </trajectory>
        <trajectory name="flag">
            <speed>240</speed>
            <easing>easeOutQuint</easing>
            <move>
                <property>opacity</property>
                <from>0</from>
                <to>1</to>
            </move>
            <move>
                <property>right</property>
                <from>96px</from>
                <to>32px</to>
            </move>
        </trajectory>
        <trajectory name="unflag">
            <speed>160</speed>
            <easing>easeInQuint</easing>
            <move>
                <property>opacity</property>
                <from>1</from>
                <to>0</to>
            </move>
            <move>
                <property>right</property>
                <from>32px</from>
                <to>0px</to>
            </move>
        </trajectory>
        <trajectory name="lock">
            <speed>200</speed>
            <easing>swing</easing>
            <move>
                <property>background-color</property>
                <to>#666</to>
            </move>
            <move>
                <property>color</property>
                <to>#eee</to>
            </move>
        </trajectory>
        <trajectory name="unlock">
            <speed>200</speed>
            <easing>swing</easing>
            <move>
                <property>background-color</property>
                <to>#eee</to>
            </move>
            <move>
                <property>color</property>
                <to>#666</to>
            </move>
        </trajectory>
    </trajectories>
    <loader>
        <dom>
            <![CDATA[
                <div class="wrapper">
                    <div class="head">
                        <label />
                        <span />
                    </div>
                    <div class="input">
                        <input type="textfield" />
                        <div class="icon focus" />
                        <div class="icon ok" />
                        <div class="icon ko" />
                        <div class="icon loading" />
                        <div class="icon locked" />
                    </div>
                    <div class="foot">-</div>
                </div>
            ]]>
        </dom>
        <action call="init" />
        <to>Initial</to>
    </loader>
    <state id="Initial">
        <trigger bind="focus">
            <target>field</target>
            <action call="select" />
            <action call="go">
                <parameter>Focus</parameter>
            </action>
        </trigger>
        <in>
            <target>wrapper</target>
            <pre call="width">
                <parameter>field</parameter>
                <parameter>-16</parameter>
            </pre>
            <pre call="center">
                <parameter>field</parameter>
            </pre>
            <pre call="center">
                <parameter>icons</parameter>
            </pre>
            <pre call="attribute">
                <parameter>field</parameter>
                <parameter>disabled</parameter>
                <parameter>disabled</parameter>
            </pre>
            <animation base="fadein" />
            <post call="attribute">
                <parameter>field</parameter>
                <parameter>disabled</parameter>
            </post>
        </in>
        <begin call="refocus" />
    </state>
    <state id="Empty">
        <begin call="check" />
    </state>
    <state id="Focus">
        <trigger bind="blur">
            <target>field</target>
            <action call="validate" />
        </trigger>
        <in>
            <target>focus</target>
            <animation base="flag" />
        </in>
        <begin call="refocus" />
        <out>
            <target>focus</target>
            <animation base="unflag" />
        </out>
    </state>
    <state id="Ok">
        <trigger bind="focus">
            <target>field</target>
            <action call="go">
                <parameter>Focus</parameter>
            </action>
        </trigger>
        <in>
            <target>ok</target>
            <animation base="flag" />
        </in>
        <begin call="refocus" />
        <out>
            <target>ok</target>
            <animation base="unflag" />
        </out>
    </state>
    <state id="Ko">
        <trigger bind="focus">
            <target>field</target>
            <action call="go">
                <parameter>Focus</parameter>
            </action>
        </trigger>
        <in>
            <target>ko</target>
            <animation base="flag" />
        </in>
        <in>
            <target>foot</target>
            <animation base="fadein" />
        </in>
        <begin call="refocus" />
        <out>
            <target>ko</target>
            <animation base="unflag" />
        </out>
        <out>
            <target>foot</target>
            <animation base="fadeout" />
        </out>
    </state>
    <state id="Checking">
        <in>
            <target>loading</target>
            <animation base="flag" />
        </in>
        <begin call="check" />
        <out>
            <target>loading</target>
            <animation base="unflag" />
        </out>
    </state>
    <state id="Locked">
        <in>
            <target>locked</target>
            <animation base="flag" />
        </in>
        <in>
            <target>field</target>
            <animation base="lock" />
        </in>
        <begin call="attribute">
            <parameter>field</parameter>
            <parameter>disabled</parameter>
            <parameter>disabled</parameter>
        </begin>
        <out>
            <target>field</target>
            <animation base="unlock" />
        </out>
        <out>
            <target>locked</target>
            <animation base="unflag" />
        </out>
        <conclude call="attribute">
            <parameter>field</parameter>
            <parameter>disabled</parameter>
        </conclude>
    </state>
</component>

=== webkawa/r2pg/web/data/components/alert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Framework native errors -->
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../data/models/components.xsd"
         type="classic" 
         name="alert" >
    
    <selectors>
        <selector id="window">div.window</selector>
        <selector id="title">div.window > div.title</selector>
        <selector id="message">div.window > div.message</selector>
        <selector id="button">div.window > div.button</selector>
    </selectors>
    <loader>
        <dom>
            <![CDATA[
                <div class="window">
                    <div class="title"></div>
                    <div class="message"></div>
                    <div class="button"></div>
                </div>
            ]]>
        </dom>
        <to>Open</to>
    </loader>
    <state id="Open">
        <trigger bind="click">
            <target>button</target>
            <action call="go" />
        </trigger>
        <in>
            <target>window</target>
            <pre call="init" />
            <pre call="focus" />
            <animation>
                <speed>500</speed>
                <easing>swing</easing>
                <move>
                    <property>opacity</property>
                    <from>0</from>
                    <to>1</to>
                </move>
            </animation>
        </in>
        <out>
            <target>window</target>
            <animation>
                <speed>500</speed>
                <easing>swing</easing>
                <move>
                    <property>opacity</property>
                    <from>1</from> 
                    <to>0</to>
                </move>
            </animation>
        </out>
    </state>
</component>

=== webkawa/r2pg/web/js/framework/components/alert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Framework native errors -->
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../data/models/components.xsd"
         type="classic" 
         name="alert" >
    
    <selectors>
        <selector id="window">div.window</selector>
        <selector id="message">div.window > div.message</selector>
        <selector id="button">div.window > div.button</selector>
    </selectors>
    <loader>
        <dom>
            <![CDATA[
                <div class="window">
                    <div class="message">Message</div>
                    <div class="button">Button</div>
                </div>
            ]]>
        </dom>
        <to>open</to>
    </loader>
    <state id="open">
        <trigger bind="click">
            <target>button</target>
            <call>
                <name>go</name>
            </call>
        </trigger>
        <out>
            <target>window</target>
            <animation>
                <speed>1000</speed>
                <easing>swing</easing>
                <move>
                    <property>opacity</property>
                    <from>1</from>
                    <to>0</to>
                </move>
            </animation>
        </out>
    </state>
</component>
